### ISSUE TITLE
A to unset doesn't always show

### ISSUE THREAD

**Issue by MikeCedonis** [mrfixit2001/recalbox_rockpi4#3]
I'm guess this is related to the GUI bug I posted before but I was setting up another Dualshock 4 controller and once in a while I noticed ES doesn't display the press A to unset. You won't be able to remove any buttons already set and need a keyboard or another configured controller to exit out. ES ended up restarting at one point while going through this.
Also is there somewhere you can be reached to ask some questions?

**Comment by mrfixit2001** [comment]
I have been working on an updated release for the Rock64 board and I've taken note of the issues you've reported. Thank you greatly for the feedback! I have included into this new build fixes for both of your issues, and I will have an updated build for the rk3399 platforms in the coming week or so which should hopefully allow you to close both concerns :)

I am available on discord in various chat servers, probably easiest to find me in the recalbox server.

**Comment by MikeCedonis** [comment]
Great to hear, thank you for help and good job!

**Comment by mrfixit2001** [comment]
Updated release coming under my new recalbox-rockchip repo. The RB devs have completely re-written a number of functions so I expect this is now resolved.
