### ISSUE TITLE
Kodi doesn't work properly

### ISSUE THREAD

**Issue by ioshomebrew** [mrfixit2001/recalbox_rockpi4#5]
When I've been trying to use Kodi, I notice the following issues

1) Wifi stops working and I cant SSH into the Rock Pi 4
2) there is no sound from HDMI or 3.5mm

**Comment by mrfixit2001** [comment]
Updated release coming under my new recalbox-rockchip repo. I'll be sure to test KODI. I've updated it to 18.5, the previous release was an alpha release of kodi.
